language: objective-c
osx_image: xcode9

env:
  global:
    - LC_CTYPE="en_US.UTF-8"
    - LANG="en_US.UTF-8"
    - WORKSPACE="SwiftJSONRPC.xcworkspace"
    - SCHEME="SwiftJSONRPC"
    - SDK="iphonesimulator"
    - DESTINATION="OS=11.0,name=iPhone 8"


script:
  - set -o pipefail
  - git submodule update --init --recursive

  - xcodebuild -version
  - xcodebuild -showsdks

  - xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" ENABLE_TESTABILITY=YES test

  - pod lib lint
