language: objective-c
osx_image: xcode11.3

env:
  global:
    - LC_CTYPE="en_US.UTF-8"
    - LANG="en_US.UTF-8"


script:
  - set -o pipefail

  - xcodebuild -version
  - xcodebuild -showsdks

  - swift test

  - pod lib lint
