language: objective-c
osx_image: xcode11.3

env:
  global:
    - LC_CTYPE="en_US.UTF-8"
    - LANG="en_US.UTF-8"
    - PROJECT="SwiftJSONRPC.xcodeproj"
    - SCHEME="SwiftJSONRPC"
    - SDK="iphonesimulator"
    - DESTINATION="OS=13.3,name=iPhone 8"


script:
  - set -o pipefail

  - carthage bootstrap --platform iOS

  - xcodebuild -version
  - xcodebuild -showsdks

  - xcodebuild -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" ENABLE_TESTABILITY=YES test

  - pod lib lint
